### ISSUE TITLE
Configlet associated with container but not with devices on CVP 2020.2

### ISSUE THREAD

**Issue by slackwei** [aristanetworks/ansible-cvp#224] opened 2020-09-01 15:27 UTC
Using AVD with CVP 2020.2 to provision a new DC2 fabric with configlet(exist) associated to top container, after the first run under CVP the configlet is associated with container but not with devices, run the playbook again with no changes then the configlet is associated with the devices.

![image](https://user-images.githubusercontent.com/15948616/91872389-cf1e7600-ec45-11ea-89e8-7fce73cbd923.png)

structured_configs/cvp_primary.yaml

CVP_CONTAINERS:
  DC2_FABRIC:
    parent_container: Tenant
    configlets:
      - ALIAS

**Comment by titom73** [comment] 2020-09-21 17:10
The behavior has not been reproduced in the lab using CV `2020.2.1`

Seems to be related to a CV side issue where inheritance is not correctly applied since the container is correctly configured.

I will go ahead and close this case.

**Closed as completed by titom73** 2020-09-21 17:10 UTC
Labels: module: cv_container
