### ISSUE TITLE
Error - the following devices do not exist in CVP | hostname contains a period

### ISSUE THREAD

**Issue by AristaJon** [aristanetworks/ansible-cvp#476] opened 2022-05-19 16:13 UTC
### Issue Summary

"Error - the following devices do not exist in CVP ['dc-hw.spine1.lab.local'"

Issue is seen when the hostname contains a '.' in the name.

Workaround is to use search_key in the task to query on the fqdn vs. the hostname.

- name: "Assign devices to containers"
     arista.cvp.cv_device_v3:
      devices: "{{CVP_DEVICES}}"
      state: present
      search_key: fqdn

### Which component(s) of AVD impacted

cv_device

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Input variables

```yaml
CVP_DEVICES:
    - fqdn: 'dc-hw.spine1.lab.local'
      parentContainerName: 'h_Spines'

 tasks:

   - name: "Assign devices to containers"
     arista.cvp.cv_device_v3:
      devices: "{{CVP_DEVICES}}"
      state: present
     register: CVP_DEVICES_DEFAULT
```

### Steps to reproduce

```shell
use a device hostname with a period '.'  in the name.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by noredistribution** [comment] 2022-07-05 15:11
thanks for raising this and sorry for the late reply! this is a known caveat and it's because with v3 the hostname is calculated based on stripping the fqdn on the first dot so in the above case the hostname will become `dc-hw` which is not correct
we'll have to update our schema to support hostnames and update the device module to support hostnames with dots

**Comment by sugetha24** [comment] 2022-09-13 18:13
related to #512

**Comment by sugetha24** [comment] 2024-02-16 16:11
Closing duplicate of #512

**Closed as completed by sugetha24** 2024-02-16 16:11 UTC
Labels: type: bug
