### ISSUE TITLE
"Unsupported parameters for (arista.cvp.cv_container) module: save_topology

### ISSUE THREAD

**Issue by roman-so** [aristanetworks/ansible-cvp#142] opened 2020-02-21 16:53 UTC
Issue Type
------
 - Question/Bug Report

Module Name
------
- cv_container

`arista.cvp` collection and Python libraries version

```
ansible 2.9.5
  config file = /scripts/ansible.cfg
  configured module search path = ['/plugins/modules', '/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.6 (default, Jun 27 2018, 22:45:12) [GCC 6.3.0]


ansible 2.9.5
  config file = /scripts/ansible.cfg
  configured module search path = ['/plugins/modules', '/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.6 (default, Jun 27 2018, 22:45:12) [GCC 6.3.0]
py3-ansible-cvp:root% 
py3-ansible-cvp:root% pip freeze
ansible==2.9.5
certifi==2019.11.28
cffi==1.14.0
chardet==3.0.4
cryptography==2.8
idna==2.8
Jinja2==2.11.1
MarkupSafe==1.1.1
pycparser==2.19
PyYAML==5.3
requests==2.22.0
six==1.14.0
treelib==1.5.5
urllib3==1.25.8


py3-ansible-cvp:root%  cat /project/arista/cvp/galaxy.yml | grep version:
version: 1.0.4

$ git version
git version 2.7.4
```

OS / Environment
------

> Build Information
> CloudVision version
> 2019.1.3
> UI version
> 1.14.1
> Build hash
> 17c4fac03
> Build time
> Jan 22, 2020 19:26:55 CET

Summary
------

Ansible failed  at module cv_container with the error:

>  "msg": "Unsupported parameters for (arista.cvp.cv_container) module: save_topology Supported parameters include: cvp_facts, mode, topology"

With either values   true or false for **save_topology**

Steps to reproduce
------

```yaml
ansible-playbook playbook.container.2019_override.yaml

```

**Playbook**
```
---
- name: Playbook to validate and demonstrate cv_container module.
  hosts: cvp
  connection: local
  gather_facts: no
  collections:
    - arista.cvp
  
  vars:
    containers_provision:
      IPFabric1:
        parent_container: Tenant
        devices:
        - arista1-Spine-1
      IPFabric:
        parent_container: Tenant
        devices:
        - arista5-Leaf-1
        - arista6-Leaf-2

  tasks:
    - name: "Gather CVP facts from {{inventory_hostname}}"
      arista.cvp.cv_facts:
      register: cvp_facts

    - name: Display CVP info
      debug:
        msg: "{{cvp_facts.ansible_facts.cvp_info}}" 

    - name: Display CVP Facts
      debug:
        msg: "{{cvp_facts}}" 

    - name: "Build Container topology on {{inventory_hostname}}"
      arista.cvp.cv_container:
        topology: '{{containers_provision}}'
        cvp_facts: '{{cvp_facts.ansible_facts}}'
        save_topology: false
        mode: override
      register: CVP_CONTAINERS_RESULT

    - name: Display tasks from cv_container
      debug:
        msg: "{{CVP_CONTAINERS_RESULT.data.tasks}}" 

    - name: 'Execute all pending tasks and wait for completion for 60 seconds'
      arista.cvp.cv_task:
        tasks: "{{ CVP_CONTAINERS_RESULT.data.tasks }}"
        wait: 60

    - name: "Refresh CVP facts from {{inventory_hostname}}"
      arista.cvp.cv_facts:
      register: cvp_facts

    - name: Display CVP Facts
      debug:
        msg: "{{cvp_facts}}" 
```

Expected results

```
Move devices without errors
```
Actual results
------

[outuput_container2019_override_false.txt](https://github.com/aristanetworks/ansible-cvp/files/4237107/outuput_container2019_override_false.txt)

```

```

**Comment by titom73** [comment] 2020-02-22 09:52
Hi @roman-so 

Because this option shall be set to `true` every time, it is has been removed starting `v1.0.3a` as stated in [release notes](https://github.com/aristanetworks/ansible-cvp/releases/tag/v1.0.3a)

Change has been tracked with issue #115 and PR #116.

**Comment by roman-so** [comment] 2020-02-22 10:17
Thank you for your reply. Like stated above, we have exactly the same behavior for save_topology to true. Should we add aditional traces ?

**Comment by titom73** [comment] 2020-02-22 10:23
This option has been removed from available options. So your task should be like this:

```yaml

    - name: "Build Container topology on {{inventory_hostname}}"
      arista.cvp.cv_container:
        topology: '{{containers_provision}}'
        cvp_facts: '{{cvp_facts.ansible_facts}}'
        mode: override
      register: CVP_CONTAINERS_RESULT
```

**Comment by roman-so** [comment] 2020-02-24 09:34
We have removed the option and we get this error:

> fatal: [cvp_2019]: FAILED! => {"changed": false, "msg": "GET: https://x.x.x.x:443/web/provisioning/getContainerInfoById.do?containerId= : Request Error: Invalid Container id"}

We have change the naming (deleted the "-") to remove the doubt but we still get the same error.

We also run other smaller playbook

```
---
- name: Playbook to validate and demonstrate cv_container module.
  hosts: cvp
  connection: local
  gather_facts: no
  collections:
    - arista.cvp
  
  vars:
    containers_provision:
      IPFabric1:
        parent_container: Tenant
        devices:
        - Spine1
      IPFabric:
        parent_container: Tenant
        devices:
        - Leaf1
        - Leaf2

  tasks:
    - name: "Gather CVP facts from {{inventory_hostname}}"
      arista.cvp.cv_facts:
      register: cvp_facts

    - name: Display CVP info
      debug:
        msg: "{{cvp_facts.ansible_facts.cvp_info}}" 

    - name: Display CVP Facts
      debug:
        msg: "{{cvp_facts}}" 

    - name: "Build Container topology on {{inventory_hostname}}"
      arista.cvp.cv_container:
        topology: '{{containers_provision}}'
        cvp_facts: '{{cvp_facts.ansible_facts}}'
        #save_topology: false
        mode: override
      register: CVP_CONTAINERS_RESULT

    - name: Display tasks from cv_container
      debug:
        msg: "{{CVP_CONTAINERS_RESULT.data.tasks}}" 

    - name: 'Execute all pending tasks and wait for completion for 60 seconds'
      arista.cvp.cv_task:
        tasks: "{{ CVP_CONTAINERS_RESULT.data.tasks }}"
        wait: 60

    - name: "Refresh CVP facts from {{inventory_hostname}}"
      arista.cvp.cv_facts:
      register: cvp_facts

    - name: Display CVP Facts
      debug:
        msg: "{{cvp_facts}}" 
```

Here it the cvp topology
![image](https://user-images.githubusercontent.com/59204786/75141383-1ce38000-56f1-11ea-880a-4a30773aaac9.png)

**Comment by titom73** [comment] 2020-02-24 15:02
Hi @roman-so ,
Will take a look at this error. I reproduced it this week end and even if we have an error message, ansible should have been executed as expected.

Change status and will work on this message as soon as possible.

Kind Regards,

**Comment by titom73** [comment] 2020-02-29 16:36
Currently working on how to reproduce issue in lab. 
Because issue is not present in all runs, a dedicated issue has been opened for dedicated tracking. (#143 )

Closing this issue

**Closed by titom73** 2020-02-29 16:36 UTC
Labels: cvp-version: Grant, module: cv_container
